# -*- coding: utf-8 -*-
"""Preprocesamiento de los Datos _Javier_Suarez.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1pIcrrVp2YsQ3kuuO-Mzlzq9FJYfTITYh

¿Podemos predecir la popularidad de una nueva pista en Spotify antes de su lanzamiento?

¿Qué características musicales influyen más en la popularidad de una pista en Spotify?

Esta pregunta busca identificar qué características específicas de las pistas musicales (como danceability, energy, loudness, valence, etc.) tienen una mayor influencia en su popularidad. Puedes utilizar técnicas de análisis de correlación y visualizaciones para descubrir estas relaciones.
¿Podemos predecir la popularidad de una nueva pista en Spotify antes de su lanzamiento?

Esta pregunta implica la construcción de un modelo de machine learning capaz de predecir la popularidad de una pista musical en base a sus características antes de que sea lanzada. Puedes utilizar algoritmos de regresión o clasificación para crear el modelo y evaluar su rendimiento.
"""



"""# Data Adquisition

"""

import pandas as pd
import numpy as np
import matplotlib as mpl
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.preprocessing import StandardScaler
import plotly.express as px
import scipy.stats as stats
import warnings

# Ignorar todas las advertencias
warnings.filterwarnings("ignore")

# Commented out IPython magic to ensure Python compatibility.
from google.colab import drive
drive.mount('/content/drive')
# %cd '/content/drive/MyDrive/Notebooks entregas Coder'

"""DataSet de Tracks de Spotify descargados de:
https://www.kaggle.com/datasets/lehaknarnauli/spotify-datasets?select=tracks.csv

Veamos un ejemplo de nuestro DataFrame.
"""

df = pd.read_csv('/content/drive/MyDrive/Notebooks entregas Coder/DataSetSpotify.csv')

df.sample(3)

"""# Descripcion de columnas y variables

# Preprocesamiento de los Datos

Veamos la estructura de DataFrame
"""

df.shape

df.info()

"""Buscamos los valores Nulos"""

df.isnull().sum().sum()

"""tenemos 71 valores ausentes en la variable 'name', como es un numero insignificante frente al conjunto de datos vamos a eliminarlos"""

df.dropna(subset=['name'], axis=0, inplace=True)

"""Valores Duplicados"""

df.duplicated().sum().sum()

"""Veamos las columnas o variables"""

df.columns

"""Empecemos por eliminar las columnas id y id_artists que no nos aportan al analisis"""

df = df.drop(['id','id_artists'], axis = 1)

"""Convertir los milisegundos en segundos"""

df['duration'] = df['duration_ms'].apply(lambda x:round(x/1000))
df.drop('duration_ms', inplace=True, axis=1)
df.duration.head(10)

"""Cambiamos el tipo de dato a formato fecha"""

df['release_date'] = pd.to_datetime(df['release_date'])
df['release_date'].dtype

"""Veamos como queda nuestro Data Frame"""

df.head(5)

"""Descripción de las columnas/Variables

name : Nombre de la pista.

artists(artista) : Los nombres de los artistas que interpretaron la pista. Si hay más de un artista, se separan por un;

popularity : La popularidad de una pista es un valor entre 0 y 100, siendo 100 la más popular . La popularidad se calcula mediante un algoritmo y se basa, en su mayor parte, en el número total de reproducciones que ha tenido la pista y cuán recientes son esas reproducciones. En términos generales, las canciones que se tocan mucho ahora tendrán una mayor popularidad que las canciones que se tocaban mucho en el pasado. Las pistas duplicadas (por ejemplo, la misma pista de un sencillo y un álbum) se clasifican de forma independiente. La popularidad del artista y del álbum se deriva matemáticamente de la popularidad de la pista.

duration_ms : La duración de la pista en milisegundos

explícit : Si la pista tiene o no letras explícitas (verdadero = sí, falso = no, no O desconocido)

dancebility : La bailabilidad describe qué tan adecuada es una pista para bailar en función de una combinación de elementos musicales que incluyen tempo, estabilidad del ritmo, fuerza del ritmo y regularidad general. Un valor de 0,0 es menos bailable y 1,0 es más bailable

energy : La energía es una medida de 0,0 a 1,0 y representa una medida perceptiva de intensidad y actividad. Por lo general, las pistas enérgicas se sienten rápidas, fuertes y ruidosas. Por ejemplo, el death metal tiene mucha energía, mientras que un preludio de Bach puntúa bajo en la escala.

loudness: la sonoridad general de una pista en decibelios (dB). Los valores de sonoridad se promedian en toda la pista y son útiles para comparar la sonoridad relativa de las pistas. El volumen es la cualidad de un sonido que es el principal correlato psicológico de la fuerza física (amplitud). Los valores típicos oscilan entre -60 y 0 db.

key : La clave en la que se encuentra la pista. Los números enteros se asignan a tonos utilizando la notación de clase de tono estándar. Por ejemplo 0 = C, 1 = C♯/D♭, 2 = D, y así sucesivamente. Si no se detectó ninguna clave, el valor es -1

mode : Mode indica la modalidad (mayor o menor) de una pista, el tipo de escala de la que se deriva su contenido melódico. Mayor está representado por 1 y menor es 0

Speechiness : Speechiness detecta la presencia de palabras habladas en una pista. Cuanto más se parece exclusivamente al habla la grabación (por ejemplo, programa de entrevistas, audiolibro, poesía), más cerca de 1,0 es el valor del atributo. Los valores superiores a 0,66 describen pistas que probablemente estén formadas en su totalidad por palabras habladas. Los valores entre 0,33 y 0,66 describen pistas que pueden contener tanto música como voz, ya sea en secciones o en capas, incluidos casos como la música rap. Los valores por debajo de 0,33 probablemente representen música y otras pistas que no sean de voz.

acústica : Una medida de confianza de 0,0 a 1,0 de si la pista es acústica. 1.0 representa una alta confianza en que la pista es acústica

instrumentalness : Predice si una pista no contiene voces. Los sonidos "Ooh" y "aah" se tratan como instrumentales en este contexto. Las pistas de rap o de palabras habladas son claramente "vocales". Cuanto más cerca esté el valor de instrumentalidad de 1,0, mayor será la probabilidad de que la pista no contenga contenido vocal.

liveness : Detecta la presencia de una audiencia en la grabación. Los valores de vivacidad más altos representan una mayor probabilidad de que la pista se interprete en vivo. Un valor por encima de 0,8 proporciona una gran probabilidad de que la pista esté en vivo

valences : Una medida de 0.0 a 1.0 que describe la positividad musical transmitida por una pista. Las pistas con una valencia alta suenan más positivas (p. ej., felices, alegres, eufóricas), mientras que las pistas con una valencia baja suenan más negativas (p. ej., tristes, deprimidas, enojadas).

tempo : El tempo general estimado de una pista en pulsaciones por minuto (BPM). En terminología musical, el tempo es la velocidad o ritmo de una pieza dada y se deriva directamente de la duración promedio del tiempo.

time_signature : una firma de tiempo estimada. El compás (medidor) es una convención de notación para especificar cuántos tiempos hay en cada compás (o compás). La signatura de compás varía de 3 a 7, lo que indica signaturas de compás de 3/4, a 7/4.

Analisis Descriptivo
"""

df.describe().T

"""Veamos graficamente con histogramas las distribuciones de nuestras variables"""

df.hist(bins = 20, color = 'green', figsize = (20, 14))

"""Junto al analisis descriptivo y a las graficas de las distribuciones de las variables, podemos sacar algunas concluciones generales del dataset:


"""

